name: Install Python with uv
description: |
  This GitHub Action installs Python using uv.
  It pins the specified Python version, caches uv files, and installs dependencies.

inputs:
  python-version:
    description: Python version
    required: true

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        python-version: ${{ inputs.python-version }}

    - name: Install Dependencies
      run: uv sync --all-groups
      shell: bash
